from app.extensions import db
from datetime import datetime

class Follow(db.Model):
    """
    Table for saving follower/followed User Ids.
    Variables:
        - follower_id: The user following.
        - followed_id: The user being followed.
        - timestamp: Time of the given follow action.
    """
    __tablename__ = 'follows'
    follower_id = db.Column(db.Integer, db.ForeignKey('user.id'),
                            primary_key=True)
    followed_id = db.Column(db.Integer, db.ForeignKey('user.id'),
                            primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    def obj_to_dict(self):
        """
        Return a dictionary containing follower/ followed user ids
        """
        return {
            "follower_id": self.follower_id,
            "followed_id": self.followed_id,
            "timestamp":self.timestamp
        }

class User(db.Model):
    """
    Table containing details of the registered users
    Variables:
        - id: Unique User Id (Autogenerated)
        - email: Email of the User
        - password: Hashed Password of the User
        - username of the user
        - firstname
        - lastname
        - intro of the user
        - phone of the user
        - posts made by the user- referenced to the 'Post' table
        - comments written by the user- referenced to the 'Comment' table
        - followed by user ids- referenced to the 'Follow' table
        - following user ids- referenced to the 'Follow' table
    """
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    username = db.Column(db.String(1000))
    firstname = db.Column(db.String(1000))
    lastname = db.Column(db.String(1000))
    intro = db.Column(db.String(10000))
    phone = db.Column(db.String(12))
    posts = db.relationship('Post', backref = 'user', lazy = True)
    comments = db.relationship('Comment', backref = 'user', lazy = True)
    followed = db.relationship('Follow',
                               foreign_keys=[Follow.follower_id],
                               backref=db.backref('follower', lazy='joined'),
                               lazy='dynamic',
                               cascade='all, delete-orphan')
    followers = db.relationship('Follow',
                              foreign_keys=[Follow.followed_id],
                              backref=db.backref('followed', lazy='joined'),
                              lazy='dynamic',
                              cascade='all, delete-orphan')

    def __repr__(self):
        return f'<User "{self.username}">'
    
    def obj_to_dict(self):
        """
        Return a dictionary containing the unique user Id, email and username of the User.
        """
        return {
            "id": self.id,
            "email": self.email,
            "username":self.username
        }
    
    def is_following(self, user):
        """
        Checks of the current user is following another user.
        """
        if user.id is None:
            return False
        return self.followed.filter_by(
            followed_id=user.id).first() is not None

    def is_followed_by(self, user):
        """
        Checks if the current user is being followed by another user.
        """
        if user.id is None:
            return False
        return self.followers.filter_by(
            follower_id=user.id).first() is not None
    
    def follow(self, user):
        """
        Adds the follow details to the Follow table when the user follows another user.
        """
        if not self.is_following(user):
            f = Follow(follower=self, followed=user)
            db.session.add(f)
            return True

    def unfollow(self, user):
        """
        Deletes the follow details from the Follow table when the user unfollows another user.
        """
        f = self.followed.filter_by(followed_id=user.id).first()
        if f:
            db.session.delete(f)
            return True
    

class Post(db.Model):
    """
    Table that stores all the posts made by the users
    Variables:
        - Id: unique Id of the post
        - title: title inputed while making the post
        - content: content of the post
        - user_id: The User making the post
        - mimetype: The file/image in the post
        - likes: Total likes in the post
        - comments: Comments in the post- refernced to the 'Comment' table.
    """
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200))
    content = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    mimetype = db.Column(db.Text, nullable=False)
    likes = db.Column(db.Integer, default=0)
    comments = db.relationship('Comment', backref = 'post', lazy = True)
    
    def __repr__(self):
        return f'<Post "{self.title}">'
    
    def obj_to_dict(self):
        """
        Returns a dictionary containing the Post Id, title, content, likes, image and user_id
        """
        return {
            "id": self.id,
            "title": self.title,
            "content":self.content,
            "likes":self.likes,
            "image":self.mimetype,
            "user_id": self.user_id,
        }  

class Comment(db.Model):
    """
    Table for storing all the comments made on posts
    Variables:
        - id: Unique Id of the Comment
        - content: The content of the comment
        - post_id: Id of the posts on which the comment is being made
        - user_id: Id of the user who is making the comment
    """
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<Comment "{self.content[:20]}...">'
    
    def obj_to_dict(self):
        """
        Returns a dictionary with the content of the comment and the user_id who made that comment
        """
        return {
            "content": self.content,
            "user_id": self.user_id,
        }
        
class TokenBlockList(db.Model):
    """
    Table for storing the Tokens that are Blacklisted
    Variables:
        - id: Unique Id of the Token
        - jti: The token
        - created_at: The time the token was blacklisted
    """
    id = db.Column(db.Integer, primary_key=True)
    jti = db.Column(db.String(36), nullable=True, index=True)
    created_at = db.Column(db.DateTime, nullable=True)

    def __repr__(self):
        return f'<TokenBlockList "{self.jti}">'
    
    def obj_to_dict(self):
        """
        Returns a dictionary with the token id, jti and the created_at time
        """
        return {
            "id":self.id,
            "jti": self.jti,
            "created_at":self.created_at,
        }